dirs:
  # paths relative to the repo
  base: "run_files"  

# contains the general, non model specific configuration parameters of the analysis
training:
  target_params: ["Om", "s8"]
  delta_loss:
    # regularization
    force_params_value: 0.0
    force_params_weight: 1.0
    jac_weight: 100.0
    jac_cond_weight: null
    cov_weight: False
    # numerical stability
    use_log_det: True
    tikhonov_regu: False
    eps: 1.0e-32

inference:
  abc:
    # for float32 this is close to the minimum logable value
    kernel_min_val: 1.0e-42
  gaussian_process:
