# contains the model specific configuration parameters for training
name: "resnet_vanilla"

training:
  n_steps: 50000
  output_every: null
  checkpoint_every: 10000
  eval_every: null
  learning_rate: 0.001
  clip_by_value: null
  clip_by_norm: null
  clip_by_global_norm: 5.0

dset:
  training:
    # for the delta loss, this is multiplied by 1 + 2 * n_params
    local_batch_size: 16
    is_cached: True
    n_readers: 32
    n_prefetch: null
    file_name_shuffle_buffer: 128
    examples_shuffle_buffer: 128
  eval:
    fiducial:
      local_batch_size: 100
      params: []
      i_noise: 2
      is_cached: False
      n_readers: 32
      n_prefetch: null
      is_eval: True
    grid:
      local_batch_size: 100
      n_readers: 32
      n_prefetch: null

model:
  name: resnet
  n_neighbors: 20
  max_checkpoints: 5
  kwargs:
    n_base_channels: 32
    # depth
    # n_downsampling: 5
    # n_cheby: 0
    n_downsampling: 3
    n_cheby: 2
    n_residuals: 5
    # misc
    poly_degree: 5
