# contains the model specific configuration parameters for training
name: "resnet_small"

training:
  n_steps: 3
  output_every: null
  checkpoint_every: null
  eval_every: null
  # for the delta loss, this is multiplied by 1 + 2 * n_params
  global_batch_size: 7
  learning_rate: 0.001
  clip_by_value: null
  clip_by_norm: null
  clip_by_global_norm: 5.0

model:
  name: resnet
  n_neighbors: 8
  params:
    n_base_channels: 16
    # depth
    n_downsampling: 3
    n_cheby: 2
    n_residuals: 2
    # misc
    poly_degree: 5
