# contains the model specific configuration parameters for training
name: "resnet_vanilla"

training:
  n_steps: 10000
  output_every: null
  checkpoint_every: 5000
  eval_every: 1
  learning_rate: 0.01
  clip_by_value: null
  clip_by_norm: null
  clip_by_global_norm: 5.0

dset:
  training:
    # for the delta loss, this is multiplied by 1 + 2 * n_params
    local_batch_size: 8
    is_cached: False
    n_readers: 8
    n_prefetch: null
    file_name_shuffle_buffer: 16
    examples_shuffle_buffer: 16
  eval:
    fiducial:
      local_batch_size: 25
      i_noise: 2
      is_cached: False
      n_readers: 8
      n_prefetch: null
      is_eval: True
    grid:
      local_batch_size: 25
      n_readers: 8
      n_prefetch: null

model:
  name: resnet
  n_neighbors: 20
  max_checkpoints: 5
  kwargs:
    n_base_channels: 32
    # depth
    n_downsampling: 5
    n_cheby: 0
    n_residuals: 5
    # misc
    poly_degree: 5
